mkdir -p output_100_notimes_moderate
mkdir -p output_100_notimes_aggressive
mkdir -p output_100_times_moderate
mkdir -p output_100_times_aggressive
mkdir -p output_10_notimes_moderate
mkdir -p output_10_notimes_aggressive
mkdir -p output_10_times_moderate
mkdir -p output_10_times_aggressive
mkdir -p output_1_notimes_moderate
mkdir -p output_1_notimes_aggressive
mkdir -p output_1_times_moderate
mkdir -p output_1_times_aggressive
# parallel 10
python3 run.py configs/config_1_times_aggressive.json
python3 run.py configs/config_1_times_moderate.json
python3 run.py configs/config_1_notimes_aggressive.json
python3 run.py configs/config_1_notimes_moderate.json
python3 run.py configs/config_10_times_aggressive.json
python3 run.py configs/config_10_times_moderate.json
python3 run.py configs/config_10_notimes_aggressive.json
python3 run.py configs/config_10_notimes_moderate.json
python3 run.py configs/config_100_times_aggressive.json
python3 run.py configs/config_100_times_moderate.json
python3 run.py configs/config_100_notimes_aggressive.json
python3 run.py configs/config_100_notimes_moderate.json