mkdir -p output_1_notimes_moderate/dists
mkdir -p output_1_notimes_aggressive/dists
mkdir -p output_1_times_moderate/dists
mkdir -p output_1_times_aggressive/dists
# parallel 10
python3 run.py configs/config_1_times_aggressive.json
python3 run.py configs/config_1_times_moderate.json
python3 run.py configs/config_1_notimes_aggressive.json
python3 run.py configs/config_1_notimes_moderate.json